### ISSUE TITLE
question about the model

### ISSUE THREAD

**Issue by melika-sce** [tdsone/extract-line-chart-data#2]
hello, thanks for this great work
I just wanted to know if you are using the [LineFormer ](https://github.com/TheJaeLal/LineFormer/tree/main) model or are there any preprocess or postprocess to correct the lines? cause the provided model by LineFormer doesn't have good results in most of my charts. any clarification would be helpful.

**Comment by tdsone** [comment]
Hey @melika-sce! Line data points are extracted using LineFormer but since these are just coordinates relative to the left upper corner of the image, I have to correct them to represent the true data displayed in the plot. That correction is done by extracting the plot area, which tells me where (0,0) is and the axis labels which tells me how to translate from pixel distances to value distances. 

Can you provide some of the plots here that did not work well for you? 

Side note: images with multiple plots don't work well, so if you are using that, I'd suggest breaking it down to single plot images.

**Comment by melika-sce** [comment]
Thank you for your good explanation, here are some examples.
![image png (2)](https://github.com/tdsone/extract-line-chart-data/assets/71076583/3948bab6-c2d6-43dd-a528-a701fecf890d)
![image png (1)](https://github.com/tdsone/extract-line-chart-data/assets/71076583/70258869-d5d2-4406-9ea1-5eb809d3de0c)
![image png](https://github.com/tdsone/extract-line-chart-data/assets/71076583/6bfc3243-d281-4600-a18b-83983e2f9b9b)
![6_Infineon-IPF042N10NF2S-DataSheet-v02_00-EN pdf](https://github.com/tdsone/extract-line-chart-data/assets/71076583/305d2898-b7a8-4e20-b052-b14257b15cf5)

I would appreciate your opinion on how to improve them.

**Comment by tdsone** [comment]
All of your problems seem to be related to Lineformer being imprecise. That
means without changing your image you would have to wait for Lineformer to
become better. Here are a few suggestions how you can change the images now
to make extraction easier:

   - image.png.2.jpeg (view on web)
   <https://github.com/tdsone/extract-line-chart-data/assets/71076583/3948bab6-c2d6-43dd-a528-a701fecf890d>:
   draw a black line (e.g. with *PowerPoint *or *Paint*) to connect the end
   and start of the broken line
   - image.png.1.jpeg (view on web)
   <https://github.com/tdsone/extract-line-chart-data/assets/71076583/70258869-d5d2-4406-9ea1-5eb809d3de0c>:
   maybe apply a mask that masks out the top left corner lines and try again
   - image.png.jpeg (view on web)
   <https://github.com/tdsone/extract-line-chart-data/assets/71076583/6bfc3243-d281-4600-a18b-83983e2f9b9b>:
   this one is more tricky. you could try removing the grid lines which seem
   to be the main problem for extraction. the best idea i have for removing
   the grid lines is that you could convert it to be all black or white pixels
   and then remove all thin lines, which are grid lines (e.g. by iteratively
   turning white-adjacent black pixels to white pixels)

I hope that helps!

Best
Timon

**Comment by melika-sce** [comment]
Thank you for your detailed response.
